# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow_Design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 480)
        MainWindow.setMinimumSize(QtCore.QSize(400, 480))
        MainWindow.setMaximumSize(QtCore.QSize(470, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bttn_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_1.sizePolicy().hasHeightForWidth())
        self.bttn_1.setSizePolicy(sizePolicy)
        self.bttn_1.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_1.setObjectName("bttn_1")
        self.gridLayout.addWidget(self.bttn_1, 3, 0, 1, 1)
        self.bttn_divid = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_divid.sizePolicy().hasHeightForWidth())
        self.bttn_divid.setSizePolicy(sizePolicy)
        self.bttn_divid.setMinimumSize(QtCore.QSize(56, 40))
        self.bttn_divid.setObjectName("bttn_divid")
        self.gridLayout.addWidget(self.bttn_divid, 2, 2, 1, 1)
        self.bttn_multi = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_multi.sizePolicy().hasHeightForWidth())
        self.bttn_multi.setSizePolicy(sizePolicy)
        self.bttn_multi.setMinimumSize(QtCore.QSize(56, 40))
        self.bttn_multi.setObjectName("bttn_multi")
        self.gridLayout.addWidget(self.bttn_multi, 2, 3, 1, 1)
        self.bttn_add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_add.sizePolicy().hasHeightForWidth())
        self.bttn_add.setSizePolicy(sizePolicy)
        self.bttn_add.setMinimumSize(QtCore.QSize(56, 40))
        self.bttn_add.setObjectName("bttn_add")
        self.gridLayout.addWidget(self.bttn_add, 2, 0, 1, 1)
        self.bttn_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_4.sizePolicy().hasHeightForWidth())
        self.bttn_4.setSizePolicy(sizePolicy)
        self.bttn_4.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_4.setObjectName("bttn_4")
        self.gridLayout.addWidget(self.bttn_4, 4, 0, 1, 1)
        self.bttn_sub = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_sub.sizePolicy().hasHeightForWidth())
        self.bttn_sub.setSizePolicy(sizePolicy)
        self.bttn_sub.setMinimumSize(QtCore.QSize(56, 40))
        self.bttn_sub.setObjectName("bttn_sub")
        self.gridLayout.addWidget(self.bttn_sub, 2, 1, 1, 1)
        self.bttn_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_7.sizePolicy().hasHeightForWidth())
        self.bttn_7.setSizePolicy(sizePolicy)
        self.bttn_7.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_7.setObjectName("bttn_7")
        self.gridLayout.addWidget(self.bttn_7, 5, 0, 1, 1)
        self.bttn_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_2.sizePolicy().hasHeightForWidth())
        self.bttn_2.setSizePolicy(sizePolicy)
        self.bttn_2.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_2.setObjectName("bttn_2")
        self.gridLayout.addWidget(self.bttn_2, 3, 1, 1, 1)
        self.bttn_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_3.sizePolicy().hasHeightForWidth())
        self.bttn_3.setSizePolicy(sizePolicy)
        self.bttn_3.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_3.setObjectName("bttn_3")
        self.gridLayout.addWidget(self.bttn_3, 3, 2, 1, 1)
        self.bttn_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_5.sizePolicy().hasHeightForWidth())
        self.bttn_5.setSizePolicy(sizePolicy)
        self.bttn_5.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_5.setObjectName("bttn_5")
        self.gridLayout.addWidget(self.bttn_5, 4, 1, 1, 1)
        self.bttn_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_6.sizePolicy().hasHeightForWidth())
        self.bttn_6.setSizePolicy(sizePolicy)
        self.bttn_6.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_6.setObjectName("bttn_6")
        self.gridLayout.addWidget(self.bttn_6, 4, 2, 1, 1)
        self.bttn_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_8.sizePolicy().hasHeightForWidth())
        self.bttn_8.setSizePolicy(sizePolicy)
        self.bttn_8.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_8.setObjectName("bttn_8")
        self.gridLayout.addWidget(self.bttn_8, 5, 1, 1, 1)
        self.bttn_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_9.sizePolicy().hasHeightForWidth())
        self.bttn_9.setSizePolicy(sizePolicy)
        self.bttn_9.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_9.setObjectName("bttn_9")
        self.gridLayout.addWidget(self.bttn_9, 5, 2, 1, 1)
        self.bttn_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_0.sizePolicy().hasHeightForWidth())
        self.bttn_0.setSizePolicy(sizePolicy)
        self.bttn_0.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_0.setObjectName("bttn_0")
        self.gridLayout.addWidget(self.bttn_0, 6, 1, 1, 1)
        self.bttn_equl = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_equl.sizePolicy().hasHeightForWidth())
        self.bttn_equl.setSizePolicy(sizePolicy)
        self.bttn_equl.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_equl.setObjectName("bttn_equl")
        self.gridLayout.addWidget(self.bttn_equl, 6, 2, 1, 1)
        self.lbl_display = QtWidgets.QLabel(self.centralwidget)
        self.lbl_display.setMinimumSize(QtCore.QSize(250, 40))
        self.lbl_display.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(16)
        self.lbl_display.setFont(font)
        self.lbl_display.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_display.setObjectName("lbl_display")
        self.gridLayout.addWidget(self.lbl_display, 1, 0, 1, 4)
        self.bttn_decim = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_decim.sizePolicy().hasHeightForWidth())
        self.bttn_decim.setSizePolicy(sizePolicy)
        self.bttn_decim.setMinimumSize(QtCore.QSize(56, 56))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bttn_decim.setFont(font)
        self.bttn_decim.setObjectName("bttn_decim")
        self.gridLayout.addWidget(self.bttn_decim, 6, 0, 1, 1)
        self.bttn_undo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_undo.sizePolicy().hasHeightForWidth())
        self.bttn_undo.setSizePolicy(sizePolicy)
        self.bttn_undo.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_undo.setObjectName("bttn_undo")
        self.gridLayout.addWidget(self.bttn_undo, 5, 3, 1, 1)
        self.bttn_clr = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_clr.sizePolicy().hasHeightForWidth())
        self.bttn_clr.setSizePolicy(sizePolicy)
        self.bttn_clr.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_clr.setObjectName("bttn_clr")
        self.gridLayout.addWidget(self.bttn_clr, 4, 3, 1, 1)
        self.bttn_clr_entry = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_clr_entry.sizePolicy().hasHeightForWidth())
        self.bttn_clr_entry.setSizePolicy(sizePolicy)
        self.bttn_clr_entry.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_clr_entry.setObjectName("bttn_clr_entry")
        self.gridLayout.addWidget(self.bttn_clr_entry, 3, 3, 1, 1)
        self.bttn_invert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttn_invert.sizePolicy().hasHeightForWidth())
        self.bttn_invert.setSizePolicy(sizePolicy)
        self.bttn_invert.setMinimumSize(QtCore.QSize(56, 56))
        self.bttn_invert.setObjectName("bttn_invert")
        self.gridLayout.addWidget(self.bttn_invert, 6, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.bttn_1, self.bttn_2)
        MainWindow.setTabOrder(self.bttn_2, self.bttn_3)
        MainWindow.setTabOrder(self.bttn_3, self.bttn_4)
        MainWindow.setTabOrder(self.bttn_4, self.bttn_5)
        MainWindow.setTabOrder(self.bttn_5, self.bttn_6)
        MainWindow.setTabOrder(self.bttn_6, self.bttn_7)
        MainWindow.setTabOrder(self.bttn_7, self.bttn_8)
        MainWindow.setTabOrder(self.bttn_8, self.bttn_9)
        MainWindow.setTabOrder(self.bttn_9, self.bttn_0)
        MainWindow.setTabOrder(self.bttn_0, self.bttn_equl)
        MainWindow.setTabOrder(self.bttn_equl, self.bttn_add)
        MainWindow.setTabOrder(self.bttn_add, self.bttn_sub)
        MainWindow.setTabOrder(self.bttn_sub, self.bttn_divid)
        MainWindow.setTabOrder(self.bttn_divid, self.bttn_multi)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.bttn_1.setText(_translate("MainWindow", "1"))
        self.bttn_divid.setText(_translate("MainWindow", "/"))
        self.bttn_multi.setText(_translate("MainWindow", "*"))
        self.bttn_add.setText(_translate("MainWindow", "+"))
        self.bttn_4.setText(_translate("MainWindow", "4"))
        self.bttn_sub.setText(_translate("MainWindow", "-"))
        self.bttn_7.setText(_translate("MainWindow", "7"))
        self.bttn_2.setText(_translate("MainWindow", "2"))
        self.bttn_3.setText(_translate("MainWindow", "3"))
        self.bttn_5.setText(_translate("MainWindow", "5"))
        self.bttn_6.setText(_translate("MainWindow", "6"))
        self.bttn_8.setText(_translate("MainWindow", "8"))
        self.bttn_9.setText(_translate("MainWindow", "9"))
        self.bttn_0.setText(_translate("MainWindow", "0"))
        self.bttn_equl.setText(_translate("MainWindow", "="))
        self.lbl_display.setText(_translate("MainWindow", "0.0"))
        self.bttn_decim.setText(_translate("MainWindow", "."))
        self.bttn_undo.setText(_translate("MainWindow", "Undo"))
        self.bttn_clr.setText(_translate("MainWindow", "Clear"))
        self.bttn_clr_entry.setText(_translate("MainWindow", "Clear\n"
"Entry"))
        self.bttn_invert.setText(_translate("MainWindow", "+/-"))
